name: Littonart
favicon: null
layout_spectrum: 0.11861397000029683
typography_spectrum: 0.39908016147091985
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.39211627491749823
  lightness: 0.04781355313025415
  saturation: 0.6644637666177005
  rhythmicContrast: 0.6768066801596433
purpose: []
