name: Littonart
favicon: null
layout_spectrum: 0.51247
typography_spectrum: 0.39908016147091985
title: littonart
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060608'
    - '#ffffff'
    - '#b7b7b7'
    - '#4e4d49'
    - '#0ef8f5'
  brandStrength: 0.39211627491749823
  lightness: 0.04781355313025415
  saturation: 0.625
  rhythmicContrast: 0.6768066801596433
purpose: []
